### ISSUE TITLE
sre_constants.error: multiple repeat

### ISSUE THREAD

**Issue by zedtux** [danielfrey/sublime-cucumber-step-finder#17]
When I'm using the shortcut `CTRL + CMD + M` in order to go to the step definition I have the following error:

``` python
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./cucumber_step_finder.py", line 61, in run
  File "./cucumber_step_finder.py", line 67, in get_line
  File "./cucumber_step_finder.py", line 82, in cut_words
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/re.py", line 245, in _compile
    raise error, v # invalid expression
sre_constants.error: multiple repeat
```

I don't know why there is this error. Nothing to do with the python 2.6 version I am using ?

**Comment by zedtux** [comment]
Bump
